version: '3.3'

services:
  nginx:
    container_name: graphingthecity
    image: nginx:1.17.8-alpine
    volumes:
      - ./build:/usr/share/nginx/html
    labels:
      domain: graphingthecity.studiole.uk
    networks:
      - traefik
networks:
  traefik:
    external:
      name: traefik_web