version: '3.3'

services:
  nginx:
    container_name: graphingthecity
    image: nginx:1.18-alpine
    volumes:
      - ./build:/usr/share/nginx/html
    labels:
      domain: graphingthecity.studiole.uk
    restart: unless-stopped
    networks:
      - public
networks:
  public:
    external:
      name: public
